fix: prevent uiscale from being zero
tooll3/t3 pull request #340
Opened 2024-01-06 15:47 UTC by ylmrx

2024-01-06 15:50 UTC, ylmrx commented
When entering a uiscale, if the user starts with '0' or '.', Tooll will parse it as a 0, and the UI will break immediately (the field lose the focus, it can't be edited anymore, the 0 value is saved to userSettings and has to be fixed manually there)

This patch prevent such situation from happening by forcing it back to some minimal value when it get to close to zero and let the edit happen entirely.

2024-01-11 22:16 UTC, pixtur requested changes
Thanks for you fix. That's a excellent and straight forward contribution.
With the T3 code base we try to follow the .net coding style guideline, It would be great if you could insert the leading zeros for consistency's sake.

2024-01-11 22:16 UTC, pixtur commented on Editor/UiContentUpdate.cs
> +            if (UserSettings.Config.UiScaleFactor < .1f) UserSettings.Config.UiScaleFactor = .1f;
```suggestion
            if (UserSettings.Config.UiScaleFactor < 0.1f) UserSettings.Config.UiScaleFactor = 0.1f;
```

2024-01-17 22:07 UTC, merged

2024-01-17 22:07 UTC, pixtur commented
Thanks!