feat: add an OscOutput operator and its example
tooll3/t3 pull request #404
Opened 2024-03-26 00:43 UTC by ylmrx

2024-03-27 21:47 UTC, pixtur requested changes
That's an excellent PR! Most of my comments are nitpicky about code-style and conventions. But there are three things that should be done:

1. The Op should implement the Dispose-Pattern and probably disconnect when disposing. (If not, it might happen that the op keeps an connection open).
2. Another problem might be that too many open connections will lead to performance issues. I'm not sure if this is true but OscInput uses a shared OscConnectionManager to pool and reusing connections. Although this optimization might be quite involved. I think we can live without that here.
3. Please implement `IStatusProvider`.  This will show a warning icon whenever the op has a problem (like a missing connection or an invalid IP address). Check [AbletonLiveSync] for an example.

2024-03-27 21:47 UTC, pixtur commented on Operators/Types/lib/io/osc/OscOutput.cs
> +        private bool _connected;
Please always move private members to the end for the class.

2024-03-27 21:47 UTC, pixtur commented on Operators/Types/lib/io/osc/OscOutput.cs
> +        private float _num_value;
```suggestion
        private float _numericValue;
```
Please follow the .net c# naming conventions and avoid short forms.

2024-03-27 21:47 UTC, pixtur commented on Operators/Types/lib/io/osc/OscOutput.cs
> +        private enum OscType
```suggestion
        private enum OscTypes
```

Please move to bottom and use plural for enumerations.

2024-03-27 21:47 UTC, pixtur commented on Operators/Types/lib/io/osc/OscOutput.cs
> +        private void Update(EvaluationContext context)
Please leave blank line after closing `}`

2024-03-27 21:47 UTC, pixtur commented on Operators/Types/lib/io/osc/OscOutput.cs
> +        public readonly InputSlot<string> Address = new InputSlot<string>();
Would `IpAddress` be a better name?

2024-03-27 21:47 UTC, pixtur commented on Operators/Types/lib/io/osc/OscOutput.cs
> +            CheckAddr(context);
```suggestion
            if(!TryGetValidAdress(IdAddress.GetValue(context), out var problem, out var address) {
               _lastErrorMessage = problem;
            }
```


I would have expected a `CheckXYZ` method to return a boolean. 
I much prefer the `TryGetXYZ` pattern being as static as possible.

2024-03-27 21:47 UTC, pixtur commented on Operators/Types/lib/io/osc/OscOutput.cs
> +                        else Log.Error("failed to build the OSC message (float): " + message.ErrorMessage);
Please start messages with an uppercase letter.

2024-03-27 21:47 UTC, pixtur commented on Operators/Types/lib/io/osc/OscOutput.cs
> +        private string _str_value;
```suggestion
        private string _stringValue;
```

2024-03-27 21:47 UTC, pixtur commented on Operators/Types/lib/io/osc/OscOutput.cs
> +        [Output(Guid = "a6679d6c-fc34-4588-ab20-5079ad8f8a03")]
Outputs should be at the beginning of the file. (I know... it's strange. It's not my convention. But at least it is one).

2024-03-28 15:25 UTC, ylmrx commented
(disregard latest commit, involving very experimental/wip/poc regarding text support for OscInput, i wanna keep this change focused on OscOutput), switching it to draft, as i might be noisy in between)

2024-03-28 17:30 UTC, ylmrx commented
> That's an excellent PR! Most of my comments are nitpicky about code-style and conventions. But there are three things that should be done:

Thanks ! :)

>     1. The Op should implement the Dispose-Pattern and probably disconnect when disposing. (If not, it might happen that the op keeps an connection open).

done.

>     2. Another problem might be that too many open connections will lead to performance issues. I'm not sure if this is true but OscInput uses a shared OscConnectionManager to pool and reusing connections. Although this optimization might be quite involved. I think we can live without that here.

The conManager is built with a server purpose in mind, and won't be much use for us here.

I'm not sure a threaded model would help us in this context, as there's no error check on the `OscRug.foobar.Send()` (we're UDP), and a given operator should address its whole traffic (all distinct IPs/port/location)

We can check a later stage, for a threaded model, if we get performance issue, but i think we're fine here.

On another, perf-related note, the operator gives a tiny glitch once in while, but seems to be related to the refresh rate of Tooll (and phase with touchosc frame rate (where you can't disable vsync) : it completely disappear when I disable vsync (in tooll) and it stays well under 1ms frame-time).

This is a general issue with OSC client (TouchOSC does that too (this is why many standalone sequencer/drumbox were attempted and failed (15ms is barely noticeable for eye, but sound like a clumsy drummer for a sequencer)

>     3. Please implement `IStatusProvider`.  This will show a warning icon whenever the op has a problem (like a missing connection or an invalid IP address). Check [AbletonLiveSync] for an example.

Done!

2024-03-28 22:35 UTC, merged

2024-03-28 22:35 UTC, pixtur commented
Awesome!